services:
    rankingowiec.twig.extension:
        class: RankingowiecBundle\Twig\Extension\RankingExtension
        arguments: ["@doctrine", "@request_stack"]
        tags:
            - { name: twig.extension }